name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"

      - run: deno fmt --check

      # setup rust
      - run: |
          rustup target add aarch64-linux-android \
          aarch64-unknown-linux-gnu riscv64gc-unknown-linux-gnu
      - run: |
          sudo apt-get update && \
          sudo apt-get -y install \
          binutils-aarch64-linux-gnu gcc-aarch64-linux-gnu g++-aarch64-linux-gnu \
          binutils-riscv64-linux-gnu gcc-riscv64-linux-gnu g++-riscv64-linux-gnu
      # atool
      - run: cd atool && cargo fmt --check
      - run: cd atool && cargo build
      - run: cd atool && cargo test

      # atool: x86_64-unknown-linux-gnu
      - run: |
          cd atool && \
          cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: atool
          path: atool/target/release/atool

      # atool: aarch64-linux-android
      - run: make atool
      - uses: actions/upload-artifact@v4
        with:
          name: atool-android-aarch64
          path: atool/target/aarch64-linux-android/release/atool

      # atool: aarch64-unknown-linux-gnu
      - run: |
          cd atool && \
          cargo build --release --target aarch64-unknown-linux-gnu
        env:
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER: aarch64-linux-gnu-gcc
          CC_aarch64_unknown_linux_gnu: aarch64-linux-gnu-gcc
          CXX_aarch64_unknown_linux_gnu: aarch64-linux-gnu-g++
      - uses: actions/upload-artifact@v4
        with:
          name: atool-aarch64
          path: atool/target/aarch64-unknown-linux-gnu/release/atool

      # atool: riscv64gc-unknown-linux-gnu
      - run: |
          cd atool && \
          cargo build --release --target riscv64gc-unknown-linux-gnu
        env:
          CARGO_TARGET_RISCV64GC_UNKNOWN_LINUX_GNU_LINKER: riscv64-linux-gnu-gcc
          CC_riscv64gc_unknown_linux_gnu: riscv64-linux-gnu-gcc
          CXX_riscv64gc_unknown_linux_gnu: riscv64-linux-gnu-g++
      - uses: actions/upload-artifact@v4
        with:
          name: atool-rv64gc
          path: atool/target/riscv64gc-unknown-linux-gnu/release/atool

      # TODO
      # # apkb-ui.zip apkb-setup.azi.zip
      # - run: make npm-setup apkb-setup-zip
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: apkb-ui
      #     path: ui-vue/dist
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: apkb-setup.azi.zip
      #     path: apkb-setup.azi.zip

      # # apkb.apk
      # - run: make apkb-apk
      # - uses: actions/upload-artifact@v4
      #   with:
      #     name: apkb-debug.apk
      #     path: apk/app/build/outputs/apk/debug/app-debug.apk

  # TODO
  # build-fdroid:
  #   needs: build
  #   runs-on: ubuntu-latest
  #   container:
  #     image: registry.gitlab.com/fdroid/fdroidserver:buildserver
  #   steps:
  #     - uses: actions/checkout@v4
